services:
  go:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - ./api/tmp:/app/tmp
    environment:
      - AIR_ROOT=/app
